[email]
# Адрес почты
email = [Адресс ящика с которого мы хотим получать письма]
# Пароль приложения Gmail
password = [Пароль приложения Gmail]

[schedule]
# Интервал проверки почты (в минутах)
check_interval_minutes = 60

# Время первой проверки (формат ЧЧ:ММ, или 0 для немедленного запуска)
# Если "0" - запустится сразу после старта службы
first_run_time = 0

# Конкретное время запуска (если нужно точное время, например "09:00", "13:30")
# Оставь пустым "", чтобы использовать интервал
run_at_time = 

[filter]
# Отправители (через запятую)
from_filter =  g1@yandex.ru, s2@mail.ru

# Ключевые слова в теме (через запятую, пусто - без фильтра)
subject_filter = 

# Искать письма за последние N дней (0 - без ограничения)
days_back = 0

[paths]
# Папка для вложений
attachments_folder = attachments

# Папка для логов
logs_folder = logs

[options]
# Удалять обработанные письма из Gmail? (true/false)
delete_processed = false

# Помечать письма как прочитанные? (true/false)
mark_as_read = true